theme: jekyll-theme-primer
title: Yelp Recommendations
description: Group #11 Final Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
